services:
  db:
    image: postgres:18-alpine
    container_name: optima-db
    env_file:
      - backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: optima-api
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

volumes:
  postgres_data: